runcmd:
    - [ sh, -c, "sudo apt-get update -y" ]
    - [ sh, -c, "sudo apt-get install docker.io -y"]
    - [ sh, -c, "sudo docker run mleontieff/cloud_computing_two --env redis_host=10.1.0.4 --env redis_port=6379"]